### ISSUE TITLE
No connection error

### ISSUE THREAD

**Issue by PeterEB** [lwmqn/mqtt-node#8]
If close the shepherd when reporting is start, it will throw _no connection_ Error.

```js
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: No connection.
    at req (/root/app/node_modules/mqtt-node/lib/request.js:18:15)
    at Object.request.notify (/root/app/node_modules/mqtt-node/lib/request.js:95:12)
    at MqttNode.notify (/root/app/node_modules/mqtt-node/lib/mqnode.js:417:20)
    at Object.reporter.checkAndReportResource (/root/app/node_modules/mqtt-node/lib/reporter.js:265:12)
    at /root/app/node_modules/mqtt-node/lib/init.js:89:30
    at process._tickCallback (node.js:355:11)
```

**Comment by PeterEB** [comment]
I forget listening `error` event.
